language: csharp
solution: "DMS Viewer.sln"
mono:
  - latest
deploy:
  provider: releases
  api_key: "$GITHUB_KEY"
  file: "$TRAVIS_BUILD_DIR/DMS Viewer/bin/Release/DMS Viewer.exe
  skip_cleanup: true
  on:
    tags: true
